### ISSUE TITLE
The folder sign is hidden

### ISSUE THREAD

**Issue by shirov10** [alk0ve/BitViewer#18]
Not sure what is the problem, but-
![image](https://user-images.githubusercontent.com/24639834/34198389-e4ec9d36-e572-11e7-970c-9c8dcf2d39b6.png)

**Comment by shirov10** [comment]
Actually it was fixed when I reopened the program, so maybe it is not a real problem

**Comment by alk0ve** [comment]
Doesn't seem to reproduce, reopen if this happens again.
Cheers.
