### ISSUE TITLE
Bigger files support

### ISSUE THREAD

**Issue by Veghit** [alk0ve/BitViewer#4]
openning files over 2GB results in array Int32 overflow.

**Comment by alk0ve** [comment]
OK, let's talk about this.
As a quick fix we should limit the file size to 2GB (or 4GB, since that's an easy fix); this is what I originally had in mind.

But, and this is maybe a separate issue, if we really want to support large files we should support files that are too big to be allocated as a single continuous chunk in memory. Do we want to do that?

**Comment by alk0ve** [comment]
By the way, are you using BitViewer at work?
I don't have a problem with it, on the contrary - that would be really cool.

**Comment by Veghit** [comment]
Didn't get a chance yet. Been working for only a couple days now. This aforementioned file is astronomical ,literaly, is galaxy spectra data.
A simple option is to limit the file size being read, and providing starting offset and size as parameters. Hopefully it won't be much of a change to implement.

**Comment by alk0ve** [comment]
OK, I think this is reasonable, just need to check if we can increase the limit to 4GB without anything in the UI breaking (I suspect that some of the properties are signed ints, but I'm not sure); if not, we'll have to stick with 2GB parts-of-files for now.

You want me to do this?

Also: galaxy spectra data? Is this space-cyber?

**Comment by alk0ve** [comment]
I took a look and it seems that we actually have two issues:
1) UI elements use signed ints as properties (for example, scroll bar position is an int) - so this means we're limited to 2GB at most (according to this we're limited to 2GB at a time anywa:y http://stackoverflow.com/questions/2415434/the-limitation-on-the-size-of-net-array)

2) The Packet class uses BitArray internally, which must be limited to MaxInt/8, so 256MB limit here

I think that if you're really interested in handling large files (which could be an interesting thing to implement) we'll need to make the Packet usage optional for now, but I'd like to hear from you first.

Meanwhile, I'll implement a file segment chooser for files larger than 256MB.

**Comment by alk0ve** [comment]
Done.
It's pretty basic but seems to handle 256 MB files with no problem (and it roughly takes 500 MB of RAM).
It's probably a good idea for you to review this, I'm pretty tired at the moment.

**Comment by Veghit** [comment]
Hey!
What do you mean by making the packet view optional?
Presenting large segments is probably good enough for now.

**Comment by alk0ve** [comment]
I meant that right now you treat everything as a pcap packet (either one large packet or, in the case of actual pcap files, many pcap packets), which uses BitArray, which limits us to 256 MB; we could handle non-pcap files differently, raising the limit back to 2 GB.

That's what I meant.

**Comment by alk0ve** [comment]
I'm closing this as large file support is implemented here:
https://github.com/alk0ve/FileBitViewer
in master.
This was a big part of the reason for the fork.
